import type {Image} from "@/types/Image";

export type Species = {
    "Fishery Management": string,
    "Habitat": string,
    "Habitat Impacts": string,
    "Image Gallery": Image[],
    "Location": string,
    "Management": string,
    "NOAA Fisheries Region": string,
    "Population": string,
    "Population Status": string,
    "Scientific Name": string,
    "Species Aliases": string,
    "Species Illustration Photo": Image,
    "Species Name": string,
    "Animal Health": string,
    "Availability": string,
    "Biology": string,
    "Bycatch": string,
    "Calories": string,
    "Carbohydrate": string,
    "Cholesterol": string,
    "Color": string,
    "Disease Treatment and Prevention": string,
    "Diseases in Salmon": string,
    "Displayed Seafood Profile Illustration": string,
    "Ecosystem Services": string,
    "Environmental Considerations": string,
    "Environmental Effects": string,
    "Farming Methods": string,
    "Fat, Total": string,
    "Feeds": string,
    "Fiber, Total Dietary": string,
    "Fishing Rate": string,
    "Harvest": string,
    "Harvest Type": string,
    "Health Benefits": string,
    "Human Health": string,
    "Physical Description": string,
    "Production": string,
    "Protein": string,
    "Quote": string,
    "Quote Background Color": string,
    "Research": string,
    "Saturated Fatty Acids, Total": string,
    "Selenium": string,
    "Serving Weight": string,
    "Servings": string,
    "Sodium": string,
    "Source": string,
    "Sugars, Total": string,
    "Taste": string,
    "Texture": string,
    "Path": string
}
